/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import audio.AePlayWave;
import audio.PlayAudio;
import java.awt.Color;
import java.awt.Font;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TICLAB4
 */
public class JuegoGato extends javax.swing.JFrame {

    int turno;
    Icon Modificar;
    Icon Modificar1;
    Icon Modificar2;
    /**
     * Creates new form JuegoGato
     */
    public JuegoGato() {
        initComponents();
        int turno = 0;

        Modificar = new ImageIcon(getClass().getResource("/images/im.png"));
        Modificar1 = new ImageIcon(getClass().getResource("/images/W.png"));
        Modificar2 = new ImageIcon(getClass().getResource("/images/imagen1.gif"));
        if (turno == 9) {

            JOptionPane.showMessageDialog(null, "Nadie Gana");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Iniciar = new javax.swing.JButton();
        Reset = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        J2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        J1 = new javax.swing.JTextField();
        Salir = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/berlioz-and-marie-the-aristocats-6441707-446-397-iloveimg-resized.gif"))); // NOI18N
        jLabel1.setText("Juego del Gato ");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 204)));
        jPanel2.setForeground(new java.awt.Color(0, 153, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        Iniciar.setBackground(new java.awt.Color(0, 102, 153));
        Iniciar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Iniciar.setText("Inicio");
        Iniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Iniciar.setMaximumSize(new java.awt.Dimension(83, 29));
        Iniciar.setMinimumSize(new java.awt.Dimension(83, 29));
        Iniciar.setPreferredSize(new java.awt.Dimension(83, 29));
        Iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarMouseExited(evt);
            }
        });
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        Reset.setBackground(new java.awt.Color(0, 102, 153));
        Reset.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Reset.setText("Reiniciar");
        Reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reset.setOpaque(true);
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResetMouseExited(evt);
            }
        });
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jugador 2 O");

        J2.setEditable(false);
        J2.setMargin(new java.awt.Insets(2, 14, 2, 14));
        J2.setMaximumSize(new java.awt.Dimension(83, 29));
        J2.setMinimumSize(new java.awt.Dimension(83, 29));
        J2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jugador 1 X");

        J1.setEditable(false);
        J1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                J1MouseExited(evt);
            }
        });
        J1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1ActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(0, 102, 153));
        Salir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setMaximumSize(new java.awt.Dimension(83, 29));
        Salir.setMinimumSize(new java.awt.Dimension(83, 29));
        Salir.setOpaque(true);
        Salir.setPreferredSize(new java.awt.Dimension(85, 25));
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Iniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(J2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(J1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setForeground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.GridLayout(3, 3));

        B1.setBackground(new java.awt.Color(255, 204, 255));
        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B1.setMaximumSize(new java.awt.Dimension(100, 150));
        B1.setMinimumSize(new java.awt.Dimension(100, 150));
        B1.setPreferredSize(new java.awt.Dimension(100, 150));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel3.add(B1);

        B2.setBackground(new java.awt.Color(255, 204, 255));
        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B2.setMaximumSize(new java.awt.Dimension(100, 150));
        B2.setMinimumSize(new java.awt.Dimension(100, 150));
        B2.setPreferredSize(new java.awt.Dimension(100, 150));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel3.add(B2);

        B3.setBackground(new java.awt.Color(255, 204, 255));
        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B3.setMaximumSize(new java.awt.Dimension(100, 150));
        B3.setMinimumSize(new java.awt.Dimension(100, 150));
        B3.setPreferredSize(new java.awt.Dimension(100, 150));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel3.add(B3);

        B4.setBackground(new java.awt.Color(255, 204, 255));
        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B4.setMaximumSize(new java.awt.Dimension(100, 150));
        B4.setMinimumSize(new java.awt.Dimension(100, 150));
        B4.setPreferredSize(new java.awt.Dimension(100, 150));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel3.add(B4);

        B5.setBackground(new java.awt.Color(255, 204, 255));
        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B5.setMaximumSize(new java.awt.Dimension(100, 150));
        B5.setMinimumSize(new java.awt.Dimension(100, 150));
        B5.setPreferredSize(new java.awt.Dimension(100, 150));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel3.add(B5);

        B6.setBackground(new java.awt.Color(255, 204, 255));
        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B6.setMaximumSize(new java.awt.Dimension(100, 150));
        B6.setMinimumSize(new java.awt.Dimension(100, 150));
        B6.setPreferredSize(new java.awt.Dimension(100, 150));
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jPanel3.add(B6);

        B7.setBackground(new java.awt.Color(255, 204, 255));
        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B7.setMaximumSize(new java.awt.Dimension(100, 150));
        B7.setMinimumSize(new java.awt.Dimension(100, 150));
        B7.setPreferredSize(new java.awt.Dimension(100, 150));
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        jPanel3.add(B7);

        B8.setBackground(new java.awt.Color(255, 204, 255));
        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B8.setMaximumSize(new java.awt.Dimension(100, 150));
        B8.setMinimumSize(new java.awt.Dimension(100, 150));
        B8.setPreferredSize(new java.awt.Dimension(100, 150));
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        jPanel3.add(B8);

        B9.setBackground(new java.awt.Color(255, 204, 255));
        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png"))); // NOI18N
        B9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B9.setMaximumSize(new java.awt.Dimension(100, 150));
        B9.setMinimumSize(new java.awt.Dimension(100, 150));
        B9.setPreferredSize(new java.awt.Dimension(100, 150));
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jPanel3.add(B9);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColorCasilla() {

        if (turno == 1) {
            J1.setBackground(Color.YELLOW);
            J1.setFont(new Font("Tahoma",0,18));
            J2.setBackground(Color.white);
            J2.setFont(new Font("Tahoma",0,11));

        } else {
            J2.setBackground(Color.YELLOW);
            J2.setFont(new Font("Tahoma",0,18));
            J1.setBackground(Color.white);
            J1.setFont(new Font("Tahoma",0,11));

        }

    }

    

    private void Sonido() {

        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cat Meowing-SoundBible.com-781322082.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void Sonido1() {

        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Golpe.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Reset() {
        if (turno == 0) {
            B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B1.setActionCommand("");

        } else {
            B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B1.setActionCommand("");
            turno = 0;

        }
        if (turno == 0) {
            B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B2.setActionCommand("");
            turno = 1;

        } else {
            B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B2.setActionCommand("");
            turno = 0;

        }

        if (turno == 0) {
            B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B3.setActionCommand("");
            turno = 1;

        } else {
            B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B3.setActionCommand("");
            turno = 0;

        }

        if (turno == 0) {
            B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B4.setActionCommand("");
            turno = 1;

        } else {
            B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B4.setActionCommand("");
            turno = 0;

        }

        if (turno == 0) {
            B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B5.setActionCommand("");
            turno = 1;

        } else {
            B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B5.setActionCommand("");
            turno = 0;

        }

        if (turno == 0) {
            B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B6.setActionCommand("");
            turno = 1;

        } else {
            B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B6.setActionCommand("");
            turno = 0;

        }
        if (turno == 0) {
            B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B7.setActionCommand("");
            turno = 1;

        } else {
            B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B7.setActionCommand("");
            turno = 0;

        }

        if (turno == 0) {
            B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B8.setActionCommand("");
            turno = 1;

        } else {
            B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B8.setActionCommand("");
            turno = 0;

        }

        if (turno == 0) {
            B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B9.setActionCommand("");
            turno = 1;

        } else {
            B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hhghjgjhghjgjhj.png")));
            B9.setActionCommand("");
            turno = 0;

        }

        J1.setText("");
        J1.setFont(new Font("Tahoma", 0, 11));
        J1.setBackground(Color.white);
        J2.setText("");
        J2.setBackground(Color.white);
        J2.setFont(new Font("Tahoma", 0, 11));
    }

    public void SonidoGanador() {
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Yeeeee.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /*Horizontales*/
 /*Verticales*/
 /*Hoblicuas*/
    public void VerificarGanador() {

        if (B1.getActionCommand() == "0" && B2.getActionCommand() == "0" && B3.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }

        if (B4.getActionCommand() == "0" && B5.getActionCommand() == "0" && B6.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }
        if (B7.getActionCommand() == "0" && B8.getActionCommand() == "0" && B9.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }
        if (B1.getActionCommand() == "0" && B4.getActionCommand() == "0" && B7.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }

        if (B2.getActionCommand() == "0" && B5.getActionCommand() == "0" && B8.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }
        if (B3.getActionCommand() == "0" && B6.getActionCommand() == "0" && B9.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }

        if (B1.getActionCommand() == "0" && B5.getActionCommand() == "0" && B9.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }
        if (B3.getActionCommand() == "0" && B5.getActionCommand() == "0" && B7.getActionCommand() == "0") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J1.getText() + " ! ");
        }
        /**
         * *************************************************************************************************************************
         */

        if (B1.getActionCommand() == "1" && B2.getActionCommand() == "1" && B3.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        } else {

        }

        if (B4.getActionCommand() == "1" && B5.getActionCommand() == "1" && B6.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        }
        if (B7.getActionCommand() == "1" && B8.getActionCommand() == "1" && B9.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        }
        if (B1.getActionCommand() == "1" && B4.getActionCommand() == "1" && B7.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        }

        if (B2.getActionCommand() == "1" && B5.getActionCommand() == "1" && B8.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        }
        if (B3.getActionCommand() == "1" && B6.getActionCommand() == "1" && B9.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        }

        if (B1.getActionCommand() == "1" && B5.getActionCommand() == "1" && B9.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        }
        if (B3.getActionCommand() == "1" && B5.getActionCommand() == "1" && B7.getActionCommand() == "1") {
            SonidoGanador();
            JOptionPane.showMessageDialog(null, " ¡ Ganaste " + J2.getText() + " ! ");
        }

    }
    private void Empate() {

        if (       (B1.getActionCommand() == "0" || B1.getActionCommand() == "1")
                && (B2.getActionCommand() == "0" || B2.getActionCommand() == "1")
                && (B3.getActionCommand() == "0" || B3.getActionCommand() == "1")
                && (B4.getActionCommand() == "0" || B4.getActionCommand() == "1")
                && (B5.getActionCommand() == "0" || B5.getActionCommand() == "1")
                && (B6.getActionCommand() == "0" || B6.getActionCommand() == "1")
                && (B7.getActionCommand() == "0" || B7.getActionCommand() == "1")
                && (B8.getActionCommand() == "0" || B8.getActionCommand() == "1")
                && (B9.getActionCommand() == "0" || B9.getActionCommand() == "1")
                ) {
            
            try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Wa.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
            JOptionPane.showMessageDialog(null, " \"Fin del juego \n para  jugar nuevamente reinicia el juego \" ", "", JOptionPane.INFORMATION_MESSAGE, Modificar2);
            
            
        }
    }


    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:

        if (B1.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B1.setActionCommand("0");
                turno = 1;
                this.VerificarGanador();
                ColorCasilla();
                 Empate();
            } else {
                B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B1.setActionCommand("1");
                turno = 0;
                this.VerificarGanador();
                ColorCasilla();
                 Empate();
            }
       
       
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }

    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:

        if (B2.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B2.setActionCommand("0");
                turno = 1;
                this.VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B2.setActionCommand("1");
                turno = 0;
                this.VerificarGanador();
                ColorCasilla();
                Empate();
            }
            
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:

        if (B3.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B3.setActionCommand("0");
                turno = 1;
                this.VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B3.setActionCommand("1");
                turno = 0;
                this.VerificarGanador();
                ColorCasilla();
                Empate();
            }
            Empate();
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:

        if (B4.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B4.setActionCommand("0");
                turno = 1;
                VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B4.setActionCommand("1");
                turno = 0;
                VerificarGanador();
                ColorCasilla();
                Empate();
            }
            
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }

    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:

        if (B5.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B5.setActionCommand("0");
                turno = 1;
                VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B5.setActionCommand("1");
                turno = 0;
                VerificarGanador();
                ColorCasilla();
                Empate();
            }
           
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:

        if (B6.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B6.setActionCommand("0");
                turno = 1;
                VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B6.setActionCommand("1");
                turno = 0;
                VerificarGanador();
                ColorCasilla();
                Empate();
            }
            
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:

        if (B7.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B7.setActionCommand("0");
                turno = 1;
                VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B7.setActionCommand("1");
                turno = 0;
                VerificarGanador();
                ColorCasilla();
                Empate();
            }
            
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:

        if (B8.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B8.setActionCommand("0");
                turno = 1;
                VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B8.setActionCommand("1");
                turno = 0;
                VerificarGanador();
                ColorCasilla();
                Empate();
            }
            
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);

        }
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:

        if (B9.getActionCommand().isEmpty()) {
            Sonido();
            if (turno == 0) {
                B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.png")));
                B9.setActionCommand("0");
                turno = 1;
                VerificarGanador();
                ColorCasilla();
                Empate();
            } else {
                B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/O.png")));
                B9.setActionCommand("1");
                turno = 0;
                VerificarGanador();
                ColorCasilla();
                Empate();
            }
            
        } else {
            Sonido1();
            JOptionPane.showMessageDialog(null, " Elige Otra Casilla ", "", JOptionPane.INFORMATION_MESSAGE, Modificar1);
           

        }


    }//GEN-LAST:event_B9ActionPerformed

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
       
       

    }//GEN-LAST:event_B1MouseClicked

    private void J1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J1ActionPerformed

    private void J2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_J2ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Reset();
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/n.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ResetActionPerformed

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ResetMouseClicked

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Super-Mario-Bros----Coin-Sound-Effect.wav");
            aw = new AePlayWave(url);
            aw.start();

            String j1 = JOptionPane.showInputDialog("Ingresa al Jugador 1");
            J1.setText(j1);

        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Super-Mario-Bros----Coin-Sound-Effect.wav");
            aw = new AePlayWave(url);
            aw.start();

            String j2 = JOptionPane.showInputDialog("Ingresa al Jugador 2");
            J2.setText(j2);

        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_IniciarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        int confirmado = JOptionPane.showConfirmDialog(null, "¿Realmente quiere salir?");
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/Cuack.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (JOptionPane.OK_OPTION == confirmado) {
            JOptionPane.showMessageDialog(null, " Adios Vuelve Pronto ", "Adios", JOptionPane.INFORMATION_MESSAGE, Modificar);
            System.exit(0);

        }
    }//GEN-LAST:event_SalirActionPerformed

    private void J1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_J1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_J1MouseExited

    private void IniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseEntered
        // TODO add your handling code here:
        
        Iniciar.setBackground(Color.pink);
        Iniciar.setFont(new Font("Arial Rounded MT Bold",0,22));
    }//GEN-LAST:event_IniciarMouseEntered

    private void IniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarMouseExited
        // TODO add your handling code here:
        Iniciar.setBackground(new Color(0,102,153));
        Iniciar.setFont(new Font("Arial Rounded MT Bold",0,18));
    }//GEN-LAST:event_IniciarMouseExited

    private void ResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseEntered
        // TODO add your handling code here:
        Reset.setBackground(Color.pink);
        Reset.setFont(new Font("Arial Rounded MT Bold",0,22));
    }//GEN-LAST:event_ResetMouseEntered

    private void ResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseExited
        // TODO add your handling code here:
        Reset.setBackground(new Color(0,102,153));
        Reset.setFont(new Font("Arial Rounded MT Bold",0,18));
    }//GEN-LAST:event_ResetMouseExited

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        // TODO add your handling code here:
        Salir.setBackground(Color.pink);
        Salir.setFont(new Font("Arial Rounded MT Bold",0,22));
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        // TODO add your handling code here:
        Salir.setBackground(new Color(0,102,153));
        Salir.setFont(new Font("Arial Rounded MT Bold",0,18));
    }//GEN-LAST:event_SalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoGato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton Iniciar;
    private javax.swing.JTextField J1;
    private javax.swing.JTextField J2;
    private javax.swing.JToggleButton Reset;
    private javax.swing.JToggleButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
